name: Waka Readme Stats

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: "waka"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LINES_OF_CODE: "True"
          IGNORED_REPOS: "uCalgaryNotes, Obsidian"
          SHOW_SHORT_INFO: "True"
          
